<?xml version="1.0" ?>
<robot name="camera_env" xmlns:xacro="http://www.ros.org/wiki/xacro"  >
    
    <xacro:arg name="topic_prefix" default="camera_1" />

    <xacro:property name="camera_base_radius" value="0.1" />
    <xacro:property name="camera_base_height" value="0.8" />
    <xacro:property name="camera_base_mass"   value="0.7" />
    
    <link name="camera_link">
        <inertial>
            <mass value="0.1" />
            <inertia ixx="0.000166667" iyy="0.000166667" izz="0.000166667" ixz="0.00"  iyz="0.00" ixy="0.00" />
        </inertial>
        <collision name="collision">
            <geometry>
                <box size="0.05 0.05 0.1" />
            </geometry>
        </collision>
            <visual name="visual">
                <geometry>
                    <box size="0.05 0.05 0.1" />
                </geometry>
            </visual>
    </link>

    <gazebo reference="camera_link">
        <sensor name="camera" type="camera">
            <update_rate>15.0</update_rate>
            <always_on>true</always_on>
             <visualize>true</visualize>
            <ignition_frame_id>camera_link_optical</ignition_frame_id>
            <pose>0.0 0.0 0 0 0 0</pose>
            <topic>$(arg topic_prefix)/raw_image</topic>
            <camera>
                <horizontal_fov>${radians(80)}</horizontal_fov>
                <image>
                    <width>1280</width>
                    <height>960</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>30</far>
                </clip>
            </camera>                
        </sensor>          
    </gazebo>

    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <link name="camera_link_optical"></link>

    <gazebo reference="camera_link">  
        <visual>
            <material> <!-- blue COLOR -->
                <ambient>0 0 1 1</ambient>
                <diffuse>0 0 1 1</diffuse>
                <specular>0 0 1 0</specular>
                <emissive>0 0 1 1</emissive>
            </material>
        </visual>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
        <selfCollide>true</selfCollide>
        <gravity>true</gravity>
    </gazebo>
     

    <link name="camera_base_link">
		<inertial>			
            <mass value="0.3"/>
            <inertia  ixx="0.002385" ixy="0.00"  ixz="0.00" iyy="0.002385" iyz="0.00" izz="0.00027" />
            
		</inertial>
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<cylinder length="${camera_base_height}" radius="${camera_base_radius}"/>
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<cylinder length="${camera_base_height}" radius="${camera_base_radius}"/>
			</geometry>
		</collision>
	</link> 

    <gazebo reference="camera_base_link">        
        <visual>
            <material> <!-- gray COLOR -->
                <ambient>0.1 0.1 0.1 1</ambient>
                <diffuse>0.1 0.1 0.1 1</diffuse>
                <specular>0.1 0.1 0.1 0</specular>
                <emissive>0.1 0.1 0.1 1</emissive>
            </material>
        </visual>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
        <selfCollide>true</selfCollide>
        <gravity>true</gravity>
    </gazebo>

    <joint name="joint_camera" type="fixed">
        <parent link="camera_base_link"/>
        <child link="camera_link"/>
        <origin xyz="0.05 0.0 ${camera_base_height/2.0}"/>
    </joint>

    <gazebo>
        <static>true</static>
    </gazebo>  
</robot>