# Clock bridge to sincronize with simulation
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

#Force torque sensors
- ros_topic_name: "/joint_1/force_torque"
  gz_topic_name: "/joint_1/force_torque"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS

- ros_topic_name: "/joint_2/force_torque"
  gz_topic_name: "/joint_2/force_torque"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS

- ros_topic_name: "/joint_3/force_torque"
  gz_topic_name: "/joint_3/force_torque"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS

- ros_topic_name: "/joint_4/force_torque"
  gz_topic_name: "/joint_4/force_torque"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS

- ros_topic_name: "/joint_5/force_torque"
  gz_topic_name: "/joint_5/force_torque"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS

- ros_topic_name: "/joint_6/force_torque"
  gz_topic_name: "/joint_6/force_torque"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS

#Environmet camera
- ros_topic_name: "camera_env/camera_info"
  gz_topic_name: "camera_env/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "camera_env/image"
  gz_topic_name: "camera_env/raw_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS  

#Depth camera 1
- ros_topic_name: "depth_camera_1/depth_image"
  gz_topic_name: "depth_camera_1/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "depth_camera_1/rgb_image"
  gz_topic_name: "depth_camera_1/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "depth_camera_1/camera_info"
  gz_topic_name: "depth_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "depth_camera_1/point_cloud"
  gz_topic_name: "depth_camera_1/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

#Depth camera 2
- ros_topic_name: "depth_camera_2/depth_image"
  gz_topic_name: "depth_camera_2/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "depth_camera_2/rgb_image"
  gz_topic_name: "depth_camera_2/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "depth_camera_2/camera_info"
  gz_topic_name: "depth_camera_2/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "depth_camera_2/point_cloud"
  gz_topic_name: "depth_camera_2/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

#Magnet plugin
- ros_topic_name: "tail/switch"
  gz_topic_name: "tail/switch"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: ROS_TO_GZ

- ros_topic_name: "tail/connection"
  gz_topic_name: "tail/connection"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: GZ_TO_ROS

- ros_topic_name: "tail/status"
  gz_topic_name: "tail/status"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: GZ_TO_ROS

- ros_topic_name: "head/switch"
  gz_topic_name: "head/switch"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: ROS_TO_GZ

- ros_topic_name: "head/connection"
  gz_topic_name: "head/connection"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: GZ_TO_ROS

- ros_topic_name: "head/status"
  gz_topic_name: "head/status"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: GZ_TO_ROS

  # Distance sensors
- ros_topic_name: "link_1_laser1"
  gz_topic_name: "link_1_laser1"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "link_1_laser1/point_cloud"
  gz_topic_name: "link_1_laser1/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "link_1_laser2"
  gz_topic_name: "link_1_laser2"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "link_1_laser2/point_cloud"
  gz_topic_name: "link_1_laser2/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "link_1_laser3"
  gz_topic_name: "link_1_laser3"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "link_1_laser3/point_cloud"
  gz_topic_name: "link_1_laser3/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "link_6_laser1"
  gz_topic_name: "link_6_laser1"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "link_6_laser1/point_cloud"
  gz_topic_name: "link_6_laser1/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "link_6_laser2"
  gz_topic_name: "link_6_laser2"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "link_6_laser2/point_cloud"
  gz_topic_name: "link_6_laser2/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "link_6_laser3"
  gz_topic_name: "link_6_laser3"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "link_6_laser3/point_cloud"
  gz_topic_name: "link_6_laser3/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
